export const main_page = {
  getStarted_window: '[data-test="user-onboarding-dialog-title"]',
  getStartedNext_button:
    '[data-test="user-onboarding-next"] > .MuiButton-label',
  onboarding_bankName: "#bankaccount-bankName-input",
  onboarding_routingNumber: "#bankaccount-routingNumber-input",
  onboarding_accountNumber: "#bankaccount-accountNumber-input",
  onboarding_submit_button: '[data-test="bankaccount-submit"]',
  onboarding_success_window: '[data-test="user-onboarding-dialog-title"]',
  sidebar_home: '[data-test="sidenav-home"]',
  sidebar_myAccount: '[data-test="sidenav-user-settings"]',
  sidebar_bankAccounts: '[data-test="sidenav-bankaccounts"]',
  sidebar_notifications: '[data-test="sidenav-notifications"]',
  sidebar_logout: '[data-test="sidenav-signout"]',
  menu_hamburger: '[ data-test="sidenav-toggle"]',
  new_transaction_button: '[data-test="nav-top-new-transaction"]',
  everyone_home: '[data-test="nav-public-tab"]',
  notification_button: '[data-test="nav-top-notifications-count"]',
  friends_home: '[data-test="nav-contacts-tab"]',
  mine_home: '[data-test="nav-personal-tab"]',
  calendar_home: '[data-test="transaction-list-filter-date-range-button"]',
  price_range: '[data-test="transaction-list-filter-amount-range-button"]',
  table_label:
    '[#root > div > main > div.MuiContainer-root.makeStyles-container-6.MuiContainer-maxWidthMd > div > div > div > div.MuiListSubheader-root.MuiListSubheader-sticky.MuiListSubheader-gutters"]',
};