export const sign_in_page = {
  logo_image: ".makeStyles-logo-3",
  title_text: ".MuiTypography-h5",
  username: "#username",
  password: "#password",
  username_title: "#username-label",
  password_title: "#password-label",
  username_validation_message: "#username-helper-text",
  password_validation_message: "#password-helper-text",
  rememberMe_checkbox: ".PrivateSwitchBase-input-14",
  signIn_button: '[data-test="signin-submit"]',
  signUp_link: '[data-test="signup"]',
  cypress_copyright: '[rel="noopener noreferrer"]',
  signIn_error: '[data-test="signin-error"]',
};
